export const LANDING = '/'
export const SKILL_SELECT = '/select-skills'
export const SIGNUP = '/signup'
export const GET_INVOLVED = '/get-involved'
export const DASHBOARD = '/dashboard'
export const MEMBER_INTERVIEW = '/member-interview'
